# Generated by Django 3.2.16 on 2024-01-05 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='agreement_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
