# Generated by Django 3.2.16 on 2024-01-24 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_deletedoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='deletedoffer',
            name='reason',
            field=models.TextField(default='Not specified'),
        ),
    ]
