# Generated by Django 3.2.16 on 2024-01-25 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_deletedoffer_reason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='address',
            new_name='email',
        ),
    ]
