# Generated by Django 3.2.16 on 2024-01-05 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_request_agreement_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='agreement_title',
            field=models.CharField(choices=[], max_length=100, null=True),
        ),
    ]
