# Generated by Django 3.2.16 on 2024-01-05 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_request_agreement_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='agreement_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
