# Generated by Django 3.2.16 on 2024-01-08 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_request_agreement_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_title', models.CharField(max_length=100)),
                ('project_information', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
