# Generated by Django 3.2.16 on 2024-01-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_auto_20240111_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='agreement_title_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
