# Generated by Django 3.2.16 on 2024-01-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_request_agreement_title_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='offer_from_api',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_title_id', models.CharField(max_length=255, unique=True)),
                ('agreement_title', models.CharField(max_length=255)),
                ('project_information', models.TextField()),
                ('employee_name', models.CharField(max_length=255)),
                ('provider_name', models.CharField(max_length=255)),
                ('contactperson', models.CharField(max_length=255)),
                ('externalperson', models.CharField(max_length=255)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dateuntil', models.DateTimeField()),
                ('notes', models.TextField()),
                ('document', models.TextField()),
                ('status', models.CharField(max_length=255)),
                ('v', models.IntegerField()),
            ],
        ),
    ]
