# Generated by Django 3.2.16 on 2024-01-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_offer_from_api'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer_from_api',
            name='dateuntil',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
