# Generated by Django 3.2.16 on 2024-01-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_remove_offer_from_api_dateuntil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer_from_api',
            name='agreement_title_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='offer_from_api',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, unique=True),
        ),
    ]
