# Generated by Django 3.2.16 on 2024-01-20 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_auto_20240116_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer_from_api',
            name='servicerequest_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.request'),
        ),
    ]
