# Generated by Django 3.2.16 on 2024-01-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_offer_from_api_servicerequest_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer_from_api',
            name='servicerequest_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
